### ISSUE TITLE
read starts up server but only a loading screen, no comic title or first scene shows

### ISSUE THREAD

**Issue by Solone** [spiraloid/Spiraloid-Toolkit-for-Blender-3DComicToolkit#11]
Read 3D comic comes up in browser but only says "3D Comic" and rotating loading box.

No comic cover shows or any scenes. whether from in Blender or externally from folder, double clicking index.html

**Comment by Solone** [comment]
![error on Blender startup](https://user-images.githubusercontent.com/9042430/124903043-d8097200-dfe3-11eb-9756-cfeeeb56bdc6.jpg)

**Comment by Solone** [comment]
above is a screen capture of just after blender startup from command line. no test scene yet. seems the server gets stuck writing the loading screen as the cmd window scrolls continuously. task manager shows 7 windows for firefox but only the load screen actually is there

**Comment by Solone** [comment]
![7 firefox windows from 3d comic toolkit](https://user-images.githubusercontent.com/9042430/124904456-51559480-dfe5-11eb-9f7b-adc3ed07c343.jpg)

firefox windows spawned from 3d comic toolkit as mentioned before

**Comment by spiraloid** [comment]
hmmm investigating

**Comment by spiraloid** [comment]
ok should be resolved with latest push.
https://github.com/spiraloid/Spiraloid-Toolkit-for-Blender-3DComicToolkit/commit/48c77522bce637bdbb69936dfafdf2851e2bb497

localHost server is now a PID under blender and if it exists, it does not start a second and only opens the browser.  seems like the most reliable way to go.
