### ISSUE TITLE
firefox still gets multiple windows and does not pass loading screen

### ISSUE THREAD

**Issue by Solone** [spiraloid/Spiraloid-Toolkit-for-Blender-3DComicToolkit#12]
![still many windows and does not pass loading screen](https://user-images.githubusercontent.com/9042430/125410026-c1d12c80-e3bc-11eb-95d8-d7ebaa7dbbce.jpg)

**Comment by Solone** [comment]
![2](https://user-images.githubusercontent.com/9042430/125411359-23de6180-e3be-11eb-822d-5883462be839.jpg)

**Comment by spiraloid** [comment]
should be fixed w last push
