### ISSUE TITLE
Idea - Black/white switch in the web page

### ISSUE THREAD

**Issue by systemik** [spiraloid/Spiraloid-Toolkit-for-Blender-3DComicToolkit#5]
I'm experimenting these day with the toolkit and it is really great. 
One idea: you may let reader to chose light/dark mode for the comics by using a switch in the webpage by changing webgl code only.

Not sure if this is something other toolkit user would want?

**Comment by spiraloid** [comment]
interesting idea!  invert mode.

**Comment by spiraloid** [comment]
I decided to make a global/local color pallete for this.   Night mode might be good someday, but I think it should be up to the author to control the color.  closing for now.
